// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yqiaylaikwpgdtuwneig.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlxaWF5bGFpa3dwZ2R0dXduZWlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyNzcwMDUsImV4cCI6MjA2Njg1MzAwNX0.4npA7-2XLl9hhyFUgGUcii7JMs9XtyG__u2RfDWtl70";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});